spring:
  data:
    mongodb:
      uri: masking
cloud:
  aws:
    s3:
      bucket: twotwo-bucket
    credentials:
      access-key: masking
      secret-key: masking
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
logging:
  level:
    com:
      amazons:
        util:
          EC2MetadataUtils: ERROR